### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by tkunstek** [bitrise-io/steps-remote-script-runner#7]
Often, remote scripts you want to run from other projects in your build are expecting the presence of curtain environment variables.  There variables would normally have existed if the script were dumped in an Xcode build script step.  Bitrise captures and renames these variables and they are found via "This step will generate these output variables:" and usable in subsequent steps in the workflow (which you already knew).

I would suggest that and additional input variable exist in this workflow step that allows you to simply rename / alias input variables. 

For a practical example see: https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Instabug.bundle/Instabug_dsym_upload.sh

I would want to export DWARF_DSYM_FILE_NAME=$BITRISE_DSYM_PATH prior to execution of this script.  This would spare me just dumping the script into a "Script" workflow step or creating an entirely new workflow integration.

**Comment by viktorbenei** [comment]
@tkunstek I don't think this should be part of this particular step - the "bitrise way" to handle this is to do the environment variable "aliasing" before the step runs, in a separate, generic step. This is important so that you don't have to implement the same feature over and over again in every step.

Right now you can do this aliasing with a Script step and `envman` - related guide: https://bitrise-io.github.io/devcenter/tips-and-tricks/expose-environment-variable/

e.g.:

```
envman add --key DWARF_DSYM_FILE_NAME --value "$BITRISE_DSYM_PATH"
```

We plan to create a separate step for this, so that you don't have to do it yourself with a Script step, hopefully we can create the "Set Environment Variable (or alias)" step in the near future.

I'll close this ticket, but if you'd have any question, please let us know!

**Comment by tkunstek** [comment]
I've tried that command and export. Could their be a bug in this tool that prevents it from consuming them?

+------------------------------------------------------------------------------+
| (10) script@1.1.3                                                            |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.1.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2016-09-22T12:36:31-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
+ envman add --key **DWARF_DSYM_FILE_NAME** --value /Users/vagrant/deploy/ChaCha.dSYM.zip
|                                                                              |
+----+--------------------------------------------------------------+----------+
| ✅  | script@1.1.3                                                 | 6.2 sec  |
+----+--------------------------------------------------------------+----------+

                                          ▼

+------------------------------------------------------------------------------+
| (11) remote-script-runner@2.0.1                                              |
+------------------------------------------------------------------------------+
| id: remote-script-runner                                                     |
| version: 2.0.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2016-09-22T12:36:36-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |

script_url: https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Instabug.bundle/Instabug_dsym_upload.sh

---------------------------------------------------
--- Executing script: https://raw.githubusercontent.com/Instabug/Instabug-iOS/master/Instabug.bundle/Instabug_dsym_upload.sh

Instabug: Started uploading dSYM
Instabug: found APP_TOKEN=REDACTED
Instabug: err: DWARF_DSYM_FOLDER_PATH or **DWARF_DSYM_FILE_NAME** not defined

**Comment by viktorbenei** [comment]
doesn't the error mean that both envs should be defined?

**Comment by tkunstek** [comment]
I'm going to pretend we didn't have this conversation (sorry)

**Comment by viktorbenei** [comment]
:D
